//
//  MainWindowController.swift
//  NekoSensei
//
//  Created by matthew carpenter on 6/21/16.
//  Copyright © 2016 matthew carpenter. All rights reserved.
//

import Cocoa

class MainWindowController: NSWindowController {
    
    @IBOutlet weak var rangeControl: NSSegmentedControl!
    @IBOutlet weak var recallModeButton: NSButton?
    @IBOutlet weak var guessField: NSTextField?
    @IBOutlet weak var configuredCounterControl: NSSegmentedControl!
    @IBOutlet weak var guessCounterControl: NSSegmentedControl?
    @IBOutlet var win: NSWindow?
    @IBOutlet weak var resultsLabel: NSTextField?
    
    var currentNumber: String?
    var currentCounter: String?

    override func windowDidLoad() {
        super.windowDidLoad()
        resultsLabel!.stringValue = ""

        // Implement this method to handle any initialization after your window controller's window has been loaded from its nib file.
    }
    
    @IBAction func repeatNumber(sender: NSButton) {
        let tts = TTS();
        if currentNumber != nil {
            tts.speak(currentNumber!)
        }
    }
    
    @IBAction func check(sender: NSButton) {
        if guessField!.stringValue == "" {
            next(NSButton())
            return
        }
        if currentNumber!.characters.count > 0 && guessField!.stringValue.characters.count > 0 {
            let parts = currentNumber!.characters.split{$0 == " "}.map(String.init)
            if parts[0] == guessField!.stringValue {
                resultsLabel!.stringValue = "Correct!"

            } else {
                resultsLabel!.stringValue = "Nope!"
            }
            guessField!.stringValue = ""
        }
    }
    
    @IBAction func next(sender: NSButton) {
        let tts = TTS()
        resultsLabel!.stringValue = ""
        guessField!.stringValue = ""
        generateNextNumber() {
            (result: String, counter: String) in
            self.currentNumber = result
            self.currentCounter = counter
            tts.speak(result)
        }
    }
    
    func generateNextNumber(completion: (result: String, counter: String) -> Void) {
        let t = Translator();
        var numbers = [String]()
        var configuredCounters = [String]()
        var number = ""
        
        if configuredCounterControl.segmentCount == 0 {
            return
        }
        
        // Figure out which counter we're going to use
        for i in 0..<configuredCounterControl.segmentCount {
            if (configuredCounterControl.isSelectedForSegment(i)) {
                let counter = configuredCounterControl?.labelForSegment(i)
                configuredCounters.append(counter!)
            }
        }
        let counter = configuredCounters[Int(arc4random_uniform(UInt32(configuredCounters.count)))]

        if (counter == "Hours") {
            
            // Hours are 1-23 and do not need to be translated
            number = String(arc4random_uniform(22) + 1) + ":00"
            completion(result: number, counter: counter)
            
        } else if (counter == "Minutes") {
            
            // Minutes are 0-59 and do not need to be translated
            completion(result: String(arc4random_uniform(58) + 1) + " 分", counter: counter)
        } else if (counter == "Age") {
            
            // Age is 0-100 and does not need to be translated
            completion(result: String(arc4random_uniform(99) + 1) + " 歳", counter: counter)
        } else {
            
            // Grab a random number in each range selected in the configuration options then push into `numbers` array.
            var hasSelectedRanges = false
            for i in 0..<rangeControl.segmentCount {
                if rangeControl.segmentCount > 0 {
                    if (rangeControl.isSelectedForSegment(i)) {
                        let number = randomNumberInRange(rangeControl.labelForSegment(i)!)
                        numbers.append(number)
                        hasSelectedRanges = true
                    }
                }
            }
            
            if !hasSelectedRanges {
                numbers.append(String(randomNumberInRange("X")))
            }
            
            // Pick a random number (could have been generated by any of the configured masked ranges)
            number = numbers[Int(arc4random_uniform(UInt32(numbers.count - 1)))]
            
            // Apply the appropriate translated counter, or append the english counter and translate if needed
            if counter == "None" {
                completion(result: number, counter: counter)
            } else if counter == "People" {
                completion(result: number + " 人", counter: counter)
            } else if counter == "Yen" {
                completion(result: number + " 円", counter: counter)
            } else {
                t.translate(number + " " + counter) {
                    (result: String) in
                    completion(result: result, counter: counter)
                }
            }
            
        }
    }

    /**
     * Generates a stringified random number based on the masked range provided
     */
    func randomNumberInRange(range: String) -> String {
        var strNumber = ""
        for i in range.characters {
            if (i == "X") {
                strNumber += String(arc4random_uniform(9))
            } else if (i == "0") {
                strNumber += "0"
            }
        }
        
        // strip leading 0's
        let intNumber = Int(strNumber)!
        strNumber = String(intNumber)
        
        return strNumber
    }

}
